/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import React from 'react';
import { Float } from '@react-three/drei';
import * as THREE from 'three';

const DLogo = (props) => {
  return (
    <Float floatIntensity={1}>
      <group position={[8, 8, 0]} scale={0.5} {...props} dispose={null}>
        <mesh>
          <extrudeGeometry 
            args={[
              new THREE.Shape([
                new THREE.Vector2(0, 0),
                new THREE.Vector2(0, 1),
                new THREE.Vector2(0.5, 1),
                new THREE.Vector2(0.7, 0.8),
                new THREE.Vector2(0.7, 0.2),
                new THREE.Vector2(0.5, 0),
              ]), 
              { 
                depth: 0.2, 
                bevelEnabled: true, 
                bevelThickness: 0.05, 
                bevelSize: 0.05 
              }
            ]} 
          />
          <meshStandardMaterial color="white" />
        </mesh>
      </group>
    </Float>
  );
};

export default DLogo;
